/**
 * Build metadata for analytics/debugging.
 *
 * AUTO-GENERATED by `app/scripts/build.js`.
 */
export const BUILD_INFO = {
  "buildId": "8e3d4a6",
  "buildConfig": "production",
  "version": "0.0.0",
  "gitSha": "8e3d4a6",
  "builtAt": "2026-01-27T00:44:20.092Z"
} as const;
