/**
 * Build metadata for analytics/debugging.
 *
 * AUTO-GENERATED by `app/scripts/build.js`.
 */
export const BUILD_INFO = {
  "buildId": "2635429",
  "buildConfig": "production",
  "version": "0.0.0",
  "gitSha": "2635429",
  "builtAt": "2026-01-28T04:53:03.057Z"
} as const;
