/**
 * Build metadata for analytics/debugging.
 *
 * AUTO-GENERATED by `app/scripts/build.js`.
 */
export const BUILD_INFO = {
  "buildId": "7c003c7",
  "buildConfig": "production",
  "version": "0.0.0",
  "gitSha": "7c003c7",
  "builtAt": "2026-01-28T04:21:39.509Z"
} as const;
