#!/usr/bin/env node
/**
 * Build script that reads NG_BUILD_CONFIG from environment
 * and runs ng build with the appropriate configuration.
 */
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const config = process.env.NG_BUILD_CONFIG || 'production';
console.log(`\n=== Building Angular with configuration: ${config} ===\n`);

try {
  // ------------------------------------------------------------
  // Generate build metadata file for runtime analytics/debugging
  // ------------------------------------------------------------
  const packageJsonPath = path.join(process.cwd(), 'package.json');
  const pkg = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));

  let gitSha = 'unknown';
  try {
    // Repo root is one level above /app
    const repoRoot = path.resolve(__dirname, '..', '..');
    gitSha = execSync('git rev-parse --short HEAD', { cwd: repoRoot, stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim() || 'unknown';
  } catch {
    // ignore (git may not be available in some build environments)
  }

  const envBuildId = process.env.BUILD || process.env.GITHUB_SHA || '';
  const buildId = (envBuildId ? String(envBuildId) : gitSha) || 'unknown';

  const buildInfo = {
    buildId,
    buildConfig: config,
    version: pkg?.version || '0.0.0',
    gitSha,
    builtAt: new Date().toISOString(),
  };

  const buildInfoPath = path.join(process.cwd(), 'src', 'environments', 'build-info.ts');
  const buildInfoTs = `/**
 * Build metadata for analytics/debugging.
 *
 * AUTO-GENERATED by \`app/scripts/build.js\`.
 */
export const BUILD_INFO = ${JSON.stringify(buildInfo, null, 2)} as const;
`;

  fs.writeFileSync(buildInfoPath, buildInfoTs, 'utf8');
  console.log(`Wrote build metadata: ${buildInfoPath}`);

  execSync(`npx ng build --configuration=${config}`, { 
    stdio: 'inherit',
    cwd: process.cwd()
  });
} catch (error) {
  process.exit(error.status || 1);
}
